###############################################
###############################################
# tool for converting the output generated by the Flight Planner plugin for QGIS to a Litchi mission.
###############################################
###############################################
# 1. Put all files exported from QGIS flight planner in same directory
# 2. Define the parameters below
# 3. ????
# 4. PROFIT!!!
###############################################
###############################################
# USER DEFINED PARAMETERS
###############################################
###############################################

# FULL PATH TO FILES EXPORTED BY QGIS
path_to_qgis_files <- "C:/Data/litchi/CSFS_ASCC/qgis_exports"

# SET THE INTERVAL (DISTANCE) BETWEEN PROJECTION CENTRES IN METERS
interval_distance_meters <- 25

###############################################
###############################################
###############################################
###############################################
###############################################
###############################################
###############################################
###############################################
###############################################
###############################################
# ????
###############################################
###############################################
# make output folder
output_fldr_temp <- paste0(path_to_qgis_files, "/", "LitchiMission")
# 
if(dir.exists(output_fldr_temp)==FALSE){
  dir.create(output_fldr_temp)
}else{ # delete all files if folder exists
  file.remove(list.files(output_fldr_temp, full.names = TRUE))
}
# load the tidyverse
library(tidyverse)
# files
flist_temp <- list.files(path_to_qgis_files, pattern = "\\.csv$")
# read and write
1:length(flist_temp) %>%
  purrr::map(function(xxx){
     read.csv(paste0(path_to_qgis_files,"/",flist_temp[xxx])) %>%
      dplyr::rename_with(tolower) %>%
      dplyr::arrange(waypoint.number) %>%
      dplyr::select(ycoord, xcoord, alt..asl..m.) %>%
      dplyr::rename(
        "latitude" = ycoord
        , "longitude" = xcoord
        , "altitude(m)" = alt..asl..m.
      ) %>%
      dplyr::mutate(
          "heading(deg)" = 360
          , "curvesize(m)" = 0
          , "rotationdir" = 0
          , "gimbalmode" = 0
          , "gimbalpitchangle" = -90
          , "actiontype1" = -1
          , "actionparam1" = 0
          , "actiontype2" = -1
          , "actionparam2" = 0
          , "actiontype3" = -1
          , "actionparam3" = 0
          , "actiontype4" = -1
          , "actionparam4" = 0
          , "actiontype5" = -1
          , "actionparam5" = 0
          , "actiontype6" = -1
          , "actionparam6" = 0
          , "actiontype7" = -1
          , "actionparam7" = 0
          , "actiontype8" = -1
          , "actionparam8" = 0
          , "actiontype9" = -1
          , "actionparam9" = 0
          , "actiontype10" = -1
          , "actionparam10" = 0
          , "actiontype11" = -1
          , "actionparam11" = 0
          , "actiontype12" = -1
          , "actionparam12" = 0
          , "actiontype13" = -1
          , "actionparam13" = 0
          , "actiontype14" = -1
          , "actionparam14" = 0
          , "actiontype15" = -1
          , "actionparam15" = 0
          , "altitudemode" = 1
          , "speed(m/s)" = 0
          , "poi_latitude" = 0
          , "poi_longitude" = 0
          , "poi_altitude(m)" = 0
          , "poi_altitudemode" = 0
          , "photo_timeinterval" = -1
          , "photo_distinterval" = as.numeric(interval_distance_meters)
      ) %>%
      write.csv(
        paste0(output_fldr_temp,"/", "LitchiMission_", flist_temp[xxx])
        , row.names = F
        , quote = F
      )
})
# clean up    
remove(list = ls())
gc()
